/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#include "wave.pb-c.h"
void   wave__wavelet_delta__init
                     (Wave__WaveletDelta         *message)
{
  static Wave__WaveletDelta init_value = WAVE__WAVELET_DELTA__INIT;
  *message = init_value;
}
size_t wave__wavelet_delta__get_packed_size
                     (const Wave__WaveletDelta *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_delta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__wavelet_delta__pack
                     (const Wave__WaveletDelta *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_delta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__wavelet_delta__pack_to_buffer
                     (const Wave__WaveletDelta *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_delta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__WaveletDelta *
       wave__wavelet_delta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__WaveletDelta *)
     protobuf_c_message_unpack (&wave__wavelet_delta__descriptor,
                                allocator, len, data);
}
void   wave__wavelet_delta__free_unpacked
                     (Wave__WaveletDelta *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_delta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__hashed_version__init
                     (Wave__HashedVersion         *message)
{
  static Wave__HashedVersion init_value = WAVE__HASHED_VERSION__INIT;
  *message = init_value;
}
size_t wave__hashed_version__get_packed_size
                     (const Wave__HashedVersion *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__hashed_version__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__hashed_version__pack
                     (const Wave__HashedVersion *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__hashed_version__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__hashed_version__pack_to_buffer
                     (const Wave__HashedVersion *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__hashed_version__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__HashedVersion *
       wave__hashed_version__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__HashedVersion *)
     protobuf_c_message_unpack (&wave__hashed_version__descriptor,
                                allocator, len, data);
}
void   wave__hashed_version__free_unpacked
                     (Wave__HashedVersion *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__hashed_version__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__wavelet_operation__init
                     (Wave__WaveletOperation         *message)
{
  static Wave__WaveletOperation init_value = WAVE__WAVELET_OPERATION__INIT;
  *message = init_value;
}
size_t wave__wavelet_operation__get_packed_size
                     (const Wave__WaveletOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__wavelet_operation__pack
                     (const Wave__WaveletOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__wavelet_operation__pack_to_buffer
                     (const Wave__WaveletOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__WaveletOperation *
       wave__wavelet_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__WaveletOperation *)
     protobuf_c_message_unpack (&wave__wavelet_operation__descriptor,
                                allocator, len, data);
}
void   wave__wavelet_operation__free_unpacked
                     (Wave__WaveletOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__wavelet_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__document_operation__init
                     (Wave__DocumentOperation         *message)
{
  static Wave__DocumentOperation init_value = WAVE__DOCUMENT_OPERATION__INIT;
  *message = init_value;
}
size_t wave__document_operation__get_packed_size
                     (const Wave__DocumentOperation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__document_operation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__document_operation__pack
                     (const Wave__DocumentOperation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__document_operation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__document_operation__pack_to_buffer
                     (const Wave__DocumentOperation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__document_operation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__DocumentOperation *
       wave__document_operation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__DocumentOperation *)
     protobuf_c_message_unpack (&wave__document_operation__descriptor,
                                allocator, len, data);
}
void   wave__document_operation__free_unpacked
                     (Wave__DocumentOperation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__document_operation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__applied_wavelet_delta__init
                     (Wave__AppliedWaveletDelta         *message)
{
  static Wave__AppliedWaveletDelta init_value = WAVE__APPLIED_WAVELET_DELTA__INIT;
  *message = init_value;
}
size_t wave__applied_wavelet_delta__get_packed_size
                     (const Wave__AppliedWaveletDelta *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__applied_wavelet_delta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__applied_wavelet_delta__pack
                     (const Wave__AppliedWaveletDelta *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__applied_wavelet_delta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__applied_wavelet_delta__pack_to_buffer
                     (const Wave__AppliedWaveletDelta *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__applied_wavelet_delta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__AppliedWaveletDelta *
       wave__applied_wavelet_delta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__AppliedWaveletDelta *)
     protobuf_c_message_unpack (&wave__applied_wavelet_delta__descriptor,
                                allocator, len, data);
}
void   wave__applied_wavelet_delta__free_unpacked
                     (Wave__AppliedWaveletDelta *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__applied_wavelet_delta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__signed_delta__init
                     (Wave__SignedDelta         *message)
{
  static Wave__SignedDelta init_value = WAVE__SIGNED_DELTA__INIT;
  *message = init_value;
}
size_t wave__signed_delta__get_packed_size
                     (const Wave__SignedDelta *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signed_delta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__signed_delta__pack
                     (const Wave__SignedDelta *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signed_delta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__signed_delta__pack_to_buffer
                     (const Wave__SignedDelta *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signed_delta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__SignedDelta *
       wave__signed_delta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__SignedDelta *)
     protobuf_c_message_unpack (&wave__signed_delta__descriptor,
                                allocator, len, data);
}
void   wave__signed_delta__free_unpacked
                     (Wave__SignedDelta *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signed_delta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__signature__init
                     (Wave__Signature         *message)
{
  static Wave__Signature init_value = WAVE__SIGNATURE__INIT;
  *message = init_value;
}
size_t wave__signature__get_packed_size
                     (const Wave__Signature *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signature__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__signature__pack
                     (const Wave__Signature *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signature__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__signature__pack_to_buffer
                     (const Wave__Signature *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signature__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__Signature *
       wave__signature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__Signature *)
     protobuf_c_message_unpack (&wave__signature__descriptor,
                                allocator, len, data);
}
void   wave__signature__free_unpacked
                     (Wave__Signature *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signature__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   wave__signer_info__init
                     (Wave__SignerInfo         *message)
{
  static Wave__SignerInfo init_value = WAVE__SIGNER_INFO__INIT;
  *message = init_value;
}
size_t wave__signer_info__get_packed_size
                     (const Wave__SignerInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signer_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t wave__signer_info__pack
                     (const Wave__SignerInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signer_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t wave__signer_info__pack_to_buffer
                     (const Wave__SignerInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signer_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Wave__SignerInfo *
       wave__signer_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Wave__SignerInfo *)
     protobuf_c_message_unpack (&wave__signer_info__descriptor,
                                allocator, len, data);
}
void   wave__signer_info__free_unpacked
                     (Wave__SignerInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &wave__signer_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor wave__wavelet_delta__field_descriptors[4] =
{
  {
    "hashedversion",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletDelta, hashedversion),
    &wave__hashed_version__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "author",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletDelta, author),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "operation",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__WaveletDelta, n_operation),
    PROTOBUF_C_OFFSETOF(Wave__WaveletDelta, operation),
    &wave__wavelet_operation__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "addresspath",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Wave__WaveletDelta, n_addresspath),
    PROTOBUF_C_OFFSETOF(Wave__WaveletDelta, addresspath),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__wavelet_delta__field_indices_by_name[] = {
  3,   /* field[3] = addressPath */
  1,   /* field[1] = author */
  0,   /* field[0] = hashedVersion */
  2,   /* field[2] = operation */
};
static const ProtobufCIntRange wave__wavelet_delta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor wave__wavelet_delta__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.WaveletDelta",
  "WaveletDelta",
  "Wave__WaveletDelta",
  "wave",
  sizeof(Wave__WaveletDelta),
  4,
  wave__wavelet_delta__field_descriptors,
  wave__wavelet_delta__field_indices_by_name,
  1,  wave__wavelet_delta__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__hashed_version__field_descriptors[2] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__HashedVersion, version),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "historyhash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__HashedVersion, historyhash),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__hashed_version__field_indices_by_name[] = {
  1,   /* field[1] = historyHash */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange wave__hashed_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wave__hashed_version__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.HashedVersion",
  "HashedVersion",
  "Wave__HashedVersion",
  "wave",
  sizeof(Wave__HashedVersion),
  2,
  wave__hashed_version__field_descriptors,
  wave__hashed_version__field_indices_by_name,
  1,  wave__hashed_version__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__wavelet_operation__mutate_document__field_descriptors[2] =
{
  {
    "documentid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation__MutateDocument, documentid),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "documentoperation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation__MutateDocument, documentoperation),
    &wave__document_operation__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__wavelet_operation__mutate_document__field_indices_by_name[] = {
  0,   /* field[0] = documentId */
  1,   /* field[1] = documentOperation */
};
static const ProtobufCIntRange wave__wavelet_operation__mutate_document__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wave__wavelet_operation__mutate_document__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.WaveletOperation.MutateDocument",
  "MutateDocument",
  "Wave__WaveletOperation__MutateDocument",
  "wave",
  sizeof(Wave__WaveletOperation__MutateDocument),
  2,
  wave__wavelet_operation__mutate_document__field_descriptors,
  wave__wavelet_operation__mutate_document__field_indices_by_name,
  1,  wave__wavelet_operation__mutate_document__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__wavelet_operation__field_descriptors[4] =
{
  {
    "addparticipant",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation, addparticipant),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "removeparticipant",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation, removeparticipant),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "mutatedocument",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation, mutatedocument),
    &wave__wavelet_operation__mutate_document__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "noop",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation, has_noop),
    PROTOBUF_C_OFFSETOF(Wave__WaveletOperation, noop),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__wavelet_operation__field_indices_by_name[] = {
  0,   /* field[0] = addParticipant */
  2,   /* field[2] = mutateDocument */
  3,   /* field[3] = noOp */
  1,   /* field[1] = removeParticipant */
};
static const ProtobufCIntRange wave__wavelet_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor wave__wavelet_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.WaveletOperation",
  "WaveletOperation",
  "Wave__WaveletOperation",
  "wave",
  sizeof(Wave__WaveletOperation),
  4,
  wave__wavelet_operation__field_descriptors,
  wave__wavelet_operation__field_indices_by_name,
  1,  wave__wavelet_operation__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__key_value_pair__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__KeyValuePair, key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__KeyValuePair, value),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__key_value_pair__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange wave__document_operation__component__key_value_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__key_value_pair__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component.KeyValuePair",
  "KeyValuePair",
  "Wave__DocumentOperation__Component__KeyValuePair",
  "wave",
  sizeof(Wave__DocumentOperation__Component__KeyValuePair),
  2,
  wave__document_operation__component__key_value_pair__field_descriptors,
  wave__document_operation__component__key_value_pair__field_indices_by_name,
  1,  wave__document_operation__component__key_value_pair__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__key_value_update__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__KeyValueUpdate, key),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "oldvalue",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__KeyValueUpdate, oldvalue),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "newvalue",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__KeyValueUpdate, newvalue),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__key_value_update__field_indices_by_name[] = {
  0,   /* field[0] = key */
  2,   /* field[2] = newValue */
  1,   /* field[1] = oldValue */
};
static const ProtobufCIntRange wave__document_operation__component__key_value_update__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__key_value_update__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component.KeyValueUpdate",
  "KeyValueUpdate",
  "Wave__DocumentOperation__Component__KeyValueUpdate",
  "wave",
  sizeof(Wave__DocumentOperation__Component__KeyValueUpdate),
  3,
  wave__document_operation__component__key_value_update__field_descriptors,
  wave__document_operation__component__key_value_update__field_indices_by_name,
  1,  wave__document_operation__component__key_value_update__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__element_start__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ElementStart, type),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "attribute",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ElementStart, n_attribute),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ElementStart, attribute),
    &wave__document_operation__component__key_value_pair__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__element_start__field_indices_by_name[] = {
  1,   /* field[1] = attribute */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange wave__document_operation__component__element_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__element_start__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component.ElementStart",
  "ElementStart",
  "Wave__DocumentOperation__Component__ElementStart",
  "wave",
  sizeof(Wave__DocumentOperation__Component__ElementStart),
  2,
  wave__document_operation__component__element_start__field_descriptors,
  wave__document_operation__component__element_start__field_indices_by_name,
  1,  wave__document_operation__component__element_start__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__replace_attributes__field_descriptors[3] =
{
  {
    "empty",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ReplaceAttributes, has_empty),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ReplaceAttributes, empty),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "oldattribute",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ReplaceAttributes, n_oldattribute),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ReplaceAttributes, oldattribute),
    &wave__document_operation__component__key_value_pair__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "newattribute",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ReplaceAttributes, n_newattribute),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__ReplaceAttributes, newattribute),
    &wave__document_operation__component__key_value_pair__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__replace_attributes__field_indices_by_name[] = {
  0,   /* field[0] = empty */
  2,   /* field[2] = newAttribute */
  1,   /* field[1] = oldAttribute */
};
static const ProtobufCIntRange wave__document_operation__component__replace_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__replace_attributes__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component.ReplaceAttributes",
  "ReplaceAttributes",
  "Wave__DocumentOperation__Component__ReplaceAttributes",
  "wave",
  sizeof(Wave__DocumentOperation__Component__ReplaceAttributes),
  3,
  wave__document_operation__component__replace_attributes__field_descriptors,
  wave__document_operation__component__replace_attributes__field_indices_by_name,
  1,  wave__document_operation__component__replace_attributes__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__update_attributes__field_descriptors[2] =
{
  {
    "empty",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__UpdateAttributes, has_empty),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__UpdateAttributes, empty),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "attributeupdate",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__UpdateAttributes, n_attributeupdate),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__UpdateAttributes, attributeupdate),
    &wave__document_operation__component__key_value_update__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__update_attributes__field_indices_by_name[] = {
  1,   /* field[1] = attributeUpdate */
  0,   /* field[0] = empty */
};
static const ProtobufCIntRange wave__document_operation__component__update_attributes__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__update_attributes__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component.UpdateAttributes",
  "UpdateAttributes",
  "Wave__DocumentOperation__Component__UpdateAttributes",
  "wave",
  sizeof(Wave__DocumentOperation__Component__UpdateAttributes),
  2,
  wave__document_operation__component__update_attributes__field_descriptors,
  wave__document_operation__component__update_attributes__field_indices_by_name,
  1,  wave__document_operation__component__update_attributes__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__annotation_boundary__field_descriptors[3] =
{
  {
    "empty",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__AnnotationBoundary, has_empty),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__AnnotationBoundary, empty),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "end",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__AnnotationBoundary, n_end),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__AnnotationBoundary, end),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "change",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__AnnotationBoundary, n_change),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component__AnnotationBoundary, change),
    &wave__document_operation__component__key_value_update__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__annotation_boundary__field_indices_by_name[] = {
  2,   /* field[2] = change */
  0,   /* field[0] = empty */
  1,   /* field[1] = end */
};
static const ProtobufCIntRange wave__document_operation__component__annotation_boundary__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__annotation_boundary__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component.AnnotationBoundary",
  "AnnotationBoundary",
  "Wave__DocumentOperation__Component__AnnotationBoundary",
  "wave",
  sizeof(Wave__DocumentOperation__Component__AnnotationBoundary),
  3,
  wave__document_operation__component__annotation_boundary__field_descriptors,
  wave__document_operation__component__annotation_boundary__field_indices_by_name,
  1,  wave__document_operation__component__annotation_boundary__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__component__field_descriptors[10] =
{
  {
    "annotationboundary",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, annotationboundary),
    &wave__document_operation__component__annotation_boundary__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "characters",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, characters),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "elementstart",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, elementstart),
    &wave__document_operation__component__element_start__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "elementend",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, has_elementend),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, elementend),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "retainitemcount",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, has_retainitemcount),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, retainitemcount),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "deletecharacters",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, deletecharacters),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "deleteelementstart",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, deleteelementstart),
    &wave__document_operation__component__element_start__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "deleteelementend",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, has_deleteelementend),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, deleteelementend),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "replaceattributes",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, replaceattributes),
    &wave__document_operation__component__replace_attributes__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "updateattributes",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation__Component, updateattributes),
    &wave__document_operation__component__update_attributes__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__component__field_indices_by_name[] = {
  0,   /* field[0] = annotationBoundary */
  1,   /* field[1] = characters */
  5,   /* field[5] = deleteCharacters */
  7,   /* field[7] = deleteElementEnd */
  6,   /* field[6] = deleteElementStart */
  3,   /* field[3] = elementEnd */
  2,   /* field[2] = elementStart */
  8,   /* field[8] = replaceAttributes */
  4,   /* field[4] = retainItemCount */
  9,   /* field[9] = updateAttributes */
};
static const ProtobufCIntRange wave__document_operation__component__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor wave__document_operation__component__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation.Component",
  "Component",
  "Wave__DocumentOperation__Component",
  "wave",
  sizeof(Wave__DocumentOperation__Component),
  10,
  wave__document_operation__component__field_descriptors,
  wave__document_operation__component__field_indices_by_name,
  1,  wave__document_operation__component__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__document_operation__field_descriptors[1] =
{
  {
    "component",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation, n_component),
    PROTOBUF_C_OFFSETOF(Wave__DocumentOperation, component),
    &wave__document_operation__component__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__document_operation__field_indices_by_name[] = {
  0,   /* field[0] = component */
};
static const ProtobufCIntRange wave__document_operation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor wave__document_operation__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.DocumentOperation",
  "DocumentOperation",
  "Wave__DocumentOperation",
  "wave",
  sizeof(Wave__DocumentOperation),
  1,
  wave__document_operation__field_descriptors,
  wave__document_operation__field_indices_by_name,
  1,  wave__document_operation__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__applied_wavelet_delta__field_descriptors[4] =
{
  {
    "signedoriginaldelta",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__AppliedWaveletDelta, signedoriginaldelta),
    &wave__signed_delta__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "hashedversionappliedat",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__AppliedWaveletDelta, hashedversionappliedat),
    &wave__hashed_version__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "operationsapplied",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__AppliedWaveletDelta, operationsapplied),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "applicationtimestamp",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__AppliedWaveletDelta, applicationtimestamp),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__applied_wavelet_delta__field_indices_by_name[] = {
  3,   /* field[3] = applicationTimestamp */
  1,   /* field[1] = hashedVersionAppliedAt */
  2,   /* field[2] = operationsApplied */
  0,   /* field[0] = signedOriginalDelta */
};
static const ProtobufCIntRange wave__applied_wavelet_delta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor wave__applied_wavelet_delta__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.AppliedWaveletDelta",
  "AppliedWaveletDelta",
  "Wave__AppliedWaveletDelta",
  "wave",
  sizeof(Wave__AppliedWaveletDelta),
  4,
  wave__applied_wavelet_delta__field_descriptors,
  wave__applied_wavelet_delta__field_indices_by_name,
  1,  wave__applied_wavelet_delta__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__signed_delta__field_descriptors[2] =
{
  {
    "delta",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__SignedDelta, delta),
    &wave__wavelet_delta__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "signature",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Wave__SignedDelta, n_signature),
    PROTOBUF_C_OFFSETOF(Wave__SignedDelta, signature),
    &wave__signature__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__signed_delta__field_indices_by_name[] = {
  0,   /* field[0] = delta */
  1,   /* field[1] = signature */
};
static const ProtobufCIntRange wave__signed_delta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor wave__signed_delta__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.SignedDelta",
  "SignedDelta",
  "Wave__SignedDelta",
  "wave",
  sizeof(Wave__SignedDelta),
  2,
  wave__signed_delta__field_descriptors,
  wave__signed_delta__field_indices_by_name,
  1,  wave__signed_delta__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
const ProtobufCEnumValue wave__signature__signature_algorithm__enum_values_by_number[1] =
{
  { "SHA1_RSA", "WAVE__SIGNATURE__SIGNATURE_ALGORITHM__SHA1_RSA", 1 },
};
static const ProtobufCIntRange wave__signature__signature_algorithm__value_ranges[] = {
{1, 0},{0, 1}
};
const ProtobufCEnumValueIndex wave__signature__signature_algorithm__enum_values_by_name[1] =
{
  { "SHA1_RSA", 0 },
};
const ProtobufCEnumDescriptor wave__signature__signature_algorithm__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "wave.Signature.SignatureAlgorithm",
  "SignatureAlgorithm",
  "Wave__Signature__SignatureAlgorithm",
  "wave",
  1,
  wave__signature__signature_algorithm__enum_values_by_number,
  1,
  wave__signature__signature_algorithm__enum_values_by_name,
  1,
  wave__signature__signature_algorithm__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__signature__field_descriptors[3] =
{
  {
    "signaturebytes",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__Signature, signaturebytes),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "signerid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__Signature, signerid),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "signaturealgorithm",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__Signature, signaturealgorithm),
    &wave__signature__signature_algorithm__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__signature__field_indices_by_name[] = {
  2,   /* field[2] = signatureAlgorithm */
  0,   /* field[0] = signatureBytes */
  1,   /* field[1] = signerId */
};
static const ProtobufCIntRange wave__signature__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wave__signature__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.Signature",
  "Signature",
  "Wave__Signature",
  "wave",
  sizeof(Wave__Signature),
  3,
  wave__signature__field_descriptors,
  wave__signature__field_indices_by_name,
  1,  wave__signature__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
const ProtobufCEnumValue wave__signer_info__hash_algorithm__enum_values_by_number[2] =
{
  { "SHA256", "WAVE__SIGNER_INFO__HASH_ALGORITHM__SHA256", 1 },
  { "SHA512", "WAVE__SIGNER_INFO__HASH_ALGORITHM__SHA512", 2 },
};
static const ProtobufCIntRange wave__signer_info__hash_algorithm__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex wave__signer_info__hash_algorithm__enum_values_by_name[2] =
{
  { "SHA256", 0 },
  { "SHA512", 1 },
};
const ProtobufCEnumDescriptor wave__signer_info__hash_algorithm__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "wave.SignerInfo.HashAlgorithm",
  "HashAlgorithm",
  "Wave__SignerInfo__HashAlgorithm",
  "wave",
  2,
  wave__signer_info__hash_algorithm__enum_values_by_number,
  2,
  wave__signer_info__hash_algorithm__enum_values_by_name,
  1,
  wave__signer_info__hash_algorithm__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor wave__signer_info__field_descriptors[3] =
{
  {
    "hashalgorithm",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__SignerInfo, hashalgorithm),
    &wave__signer_info__hash_algorithm__descriptor,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "domain",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Wave__SignerInfo, domain),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
  {
    "certificate",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Wave__SignerInfo, n_certificate),
    PROTOBUF_C_OFFSETOF(Wave__SignerInfo, certificate),
    NULL,
    NULL,
    NULL,NULL    /* reserved1, reserved2 */
  },
};
static const unsigned wave__signer_info__field_indices_by_name[] = {
  2,   /* field[2] = certificate */
  1,   /* field[1] = domain */
  0,   /* field[0] = hashAlgorithm */
};
static const ProtobufCIntRange wave__signer_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor wave__signer_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "wave.SignerInfo",
  "SignerInfo",
  "Wave__SignerInfo",
  "wave",
  sizeof(Wave__SignerInfo),
  3,
  wave__signer_info__field_descriptors,
  wave__signer_info__field_indices_by_name,
  1,  wave__signer_info__number_ranges,
  NULL,NULL,NULL,NULL    /* reserved[1234] */
};
